# Generated by Django 5.1 on 2025-12-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ranged_dice_mod', models.IntegerField(default=0, help_text='Dice modifier for ranged attacks (+/-d6).')),
                ('melee_dice_mod', models.IntegerField(default=0, help_text='Dice modifier for melee attacks (+/-d6).')),
                ('armor', models.IntegerField(default=0, help_text='Armor value applied to injury rolls.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
