# Generated by Django 5.1 on 2025-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_default_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ranged_dice_mod', models.IntegerField(default=0, help_text='Dice modifier for ranged attacks (+/-d6).')),
                ('melee_dice_mod', models.IntegerField(default=0, help_text='Dice modifier for melee attacks (+/-d6).')),
                ('armor_mod', models.IntegerField(default=0, help_text='Armor modifier applied to injury rolls.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='unitprofile',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='unit_profiles', to='calculator.keyword'),
        ),
    ]
