# Generated by Django 5.1 on 2025-12-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_keyword_unitprofile_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weapon_type', models.CharField(choices=[('one_handed', 'One-handed'), ('two_handed', 'Two-handed')], default='one_handed', max_length=20)),
                ('range_type', models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged')], default='melee', max_length=10)),
                ('range_inches', models.PositiveIntegerField(blank=True, help_text='Range in inches for ranged weapons; leave empty for melee.', null=True)),
                ('keywords', models.ManyToManyField(blank=True, related_name='weapons', to='calculator.keyword')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
