# Generated by Django 5.1 on 2025-12-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitprofile',
            name='weapons',
            field=models.ManyToManyField(blank=True, related_name='unit_profiles', to='calculator.weapon'),
        ),
    ]
